MindBliss/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.home, name='index'),
    path('about/',  views.about, name='about'),
    path('signup_patient/',  views.signup_patient, name='signup_patient'),
    path('login/',  views.loginView, name='login'),  
    path('logout/',  views.logoutView, name='logout'),
    path('signup_psychologist/',  views.signup_psychologist,
         name='signup_psychologist'), 
    path('contact_us/',  views.contactUsView,
         name='contact_us'), 
    path('search_patient/',  views.searchPatient, name='search_patient'),
    path('create_blog/',  views.ceateBlogView,
         name='create_blog'),
    path('view_blogs/',  views.viewBlogs, 
         name='view_blogs'),
    path('serch_psychologist/',  views.searchPsychologist,
         name='serch_psychologist'),
    path('create_userstory/<int:id>',  views.createUserStory, 
         name='create_userstory'), 
    path('view_psychologist/<int:id>', 
         views.viewPsychologist, name='view_psychologist'),
    path('create_appointment/<int:id>',
         views.createAppointment, name='create_appointment'),
    path('charge/<int:id>',
         views.charge, name='charge'),
    path('chatdoc/<int:id>',  views.doctorChat,
         name='chatdoc'),
    path('chatpatient/<int:id>',  views.patientChat,
         name='chatpatient'),
    path('chatbox/',  views.chatBox,
         name='chatbox'),
    path('anxiety/',  views.Anxiety,
         name='anxiety'),
    path('personality/',  views.Personality,
         name='personality'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Patient(models.Model):
    genderOption = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other') 
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    contact_number = models.CharField(max_length=13)
    gender = models.CharField(
        max_length=10, choices=genderOption, default='Male')
    age = models.SmallIntegerField(null=True)
    email = models.CharField(max_length=100)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

 
class Psychologist(models.Model):
    genderOption = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    ) 
    session_feeOption = (
        ('500', '500'),
        ('1000', '1000'),
        ('2000', '2000'),
        ('3000', '3000'),
        ('4000', '4000'),
        ('4000', '4000'),
        ('6000', '6000'),
        ('7000', '7000'),
        ('8000', '8000'),
        ('9000', '9000'),
        ('10000', '10000')
    )
    specializationOption = (
        ('CLINICAL PSYCHOLOGY', 'CLINICAL PSYCHOLOGY'),
        ('COUNSELING PSYCHOLOGY', 'COUNSELING PSYCHOLOGY'),
        ('DEVELOPMENTAL PSYCHOLOGY', 'DEVELOPMENTAL PSYCHOLOGY'),
        ('EDUCATIONAL PSYCHOLOGY', 'EDUCATIONAL PSYCHOLOGY'),
        ('EVIRONMENTAL PSYCHOLOGY', 'EVIRONMENTAL PSYCHOLOGY'),
        ('EXPERIMENTAL PSYCHOLOGY', 'EXPERIMENTAL PSYCHOLOGY'),
        ('FORENSIC PSYCHOLOGY', 'FORENSIC PSYCHOLOGY'),
        ('HUMAN FACTORS PSYCHOLOGY', 'HUMAN FACTORS PSYCHOLOGY'),
        ('SCHOOL PSYCHOLOGY', 'SCHOOL PSYCHOLOGY'),
        ('SOCIAL PSYCHOLOGY', 'SOCIAL PSYCHOLOGY'),
        ('SPORT PSYCHOLOGY', 'SPORT PSYCHOLOGY')
    )
    degreeOption = (
        ('BS PSYCHOLOGY', 'BS PSYCHOLOGY'), 
        ('MS PSYCHOLOGY', 'MS PSYCHOLOGY'),
        ('PHD PSYCHOLOGY', 'PHD PSYCHOLOGY')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    contact_number = models.CharField(max_length=13)
    gender = models.CharField(
        max_length=10, choices=genderOption, default='Male')
    age = models.SmallIntegerField(null=True)
    phone = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100)
    date_created = models.DateField(auto_now_add=True)
    cnic = models.CharField(max_length=100)
    session_fee = models.CharField(
        max_length=10,  choices=session_feeOption, default='500',)
    specialization = models.CharField(
        max_length=100,  choices=specializationOption,  default='SPORT PSYCHOLOGY')
    degree = models.CharField(
        max_length=100, choices=degreeOption,  default='BS PSYCHOLOGY'
    )
    bio = models.TextField(max_length=200, default=".")


    def __str__(self):
        return self.name
 

class UserStory(models.Model):
    psychologist = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='assignee')
    paitent = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='creator')
    star = models.IntegerField()
    comment = models.TextField(max_length=1500, default='.')

    def __str__(self):
        return self.comment  


class Blog(models.Model):
    psychologist_id = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2000)

    def __str__(self):
        return self.title


class ContactForm(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.CharField(max_length=100)

    def __str__(self): 
        return self.message
 
 
class Appointment(models.Model):
    psychologist = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, default="" , related_name='assignee1')
    paitent = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, default="", related_name='creator1')
    time = models.TimeField()
    date = models.DateField()
    approved = models.BooleanField(default=False)

    # def __str__(self): 
    #     return self.time
 

class Charge(models.Model):
    appointment = models.ForeignKey(
        Appointment, on_delete=models.SET_NULL, null=True, default="")
    amount = models.CharField(max_length=100)
    currency = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    # def __str__(self):
    #     return description
   

templates/Anxiety.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 

<div class="login">    
    <form id='form' method="POST" style="text-align: left !important;">
    {% csrf_token %}
        <p>Q1. Feeling nervous, anxious, or on edge?</p>
        <label class="mb-4"><input type="radio" name="one" value="1" > Yes </label>
        <label><input type="radio" name="one" value="0" > No </label>

        <p>Q2. Not being able to stop or control worrying?</p>
        <label class="mb-4">
            <input type="radio" name="two" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="two" value="0">
            No
        </label>    

        <p>Q3. Worrying too much about different things?</p>
        <label class="mb-4">
            <input type="radio" name="three" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="three" value="0">
            No
        </label>

        <p>Q4. Trouble relaxing?</p>
        <label class="mb-4">
            <input type="radio" name="four" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="four" value="0">
            No
        </label> 
        <p>Q5. Being so restless that it is hard to sit still?</p>
        <label class="mb-4">
            <input type="radio" name="five" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="five" value="0">
            No
        </label>
        <p>Q6. Becoming easily annoyed or irritable?</p>
        <label class="mb-4">
            <input type="radio" name="six" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="six" value="0">
            No
        </label>
        <p>Q7. Feeling afraid, as if something awful might happen?</p>
        <label class="">
            <input type="radio" name="seven" value="1">
            Yes
            </label>
            <label>
            <input type="radio" name="seven" value="1">
            No
        </label>

        <br>
        <br>
        <br>
        <input type="submit" class="btn btn-outline-primary" value="submit">
    </form>

</div>
    
{% endblock %}
  

templates/Footer.html
<footer class="footer-distributed">
  <div class="footer-left">
    <h3>MIND<span>BLISS</span></h3>


    </p>

  </div>

  <div class="footer-center">
    <div>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>+1 555 123456</p>
    </div> 

    <div>
      <i class="fa fa-envelope"></i>
      <p>
        <a href="mailto:support@company.com">contact@mindbliss.com</a>
      </p>
    </div>
  </div>

  <div class="footer-right">
  <p></p>
    <p class="footer-company-name">mindbliss &copy; 2021</p>


  </div>
</footer>

templates/base.html
{% load static %}
<html>
  <head> 
    <title>MindBliss</title>
    <meta charset="UTF-8" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/new_styles.css' %}" />    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

  </head>
  <body style="background-image: url('{% static 'img/background5.png' %}')">

    {% include "Header.html" %}

    {% for message in messages %} 
        <p id="messages" style="color: red; font-size: 24px; font-weight: bold; "> {{message}} </p>
    {% endfor %} 

    {% block content %} 
    
    {% endblock %}

    {% include "Footer.html" %}   

    <script>
      $(".slider").owlCarousel({
        loop: true,
        autoplay: true,
        autoplayTimeout: 3000, 
        autoplayHoverPause: true,
      });
      $('input[type=text]').addClass('form-control');
      $('input[type=password]').addClass('form-control');
      $('textarea').addClass('form-control');
      $('input[type=text]').addClass('w-100');
      $('input[type=submit]').addClass('w-100');
      $('input[type=submit]').addClass('btn');
      $('input[type=submit]').addClass('btn-outline-primary');
    </script>
  </body>
</html>

  

templates/chatpatient.html
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/8.3.3/firebase-app.js"></script>

<!-- include firebase DB -->
<script src="https://www.gstatic.com/firebasejs/8.3.3/firebase-database.js"></script>

<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    apiKey: "AIzaSyAsHtWkVN-en4PmRga2CF0TccF6QbtuBFg",
    authDomain: "my-test-project-6359c.firebaseapp.com",
    projectId: "my-test-project-6359c",
    storageBucket: "my-test-project-6359c.appspot.com",
    messagingSenderId: "669682697646",
    appId: "1:669682697646:web:470739876f4741b941743f",
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
</script>

<script>
  let user = "{{ patient.user.id }}";
  let psychologist = "{{ request.user.id }}";
  let userName = "{{ request.user }}";

  function sendMessage() {
    var message = document.getElementById("message").value;

    firebase.database().ref(`${user}-${psychologist}`).push().set({
      sender: "PS",
      message: message,
    });

    document.getElementById("message").value = "";
    return false;
  }

  firebase
    .database() 
    .ref(`${user}-${psychologist}`)
    .on("child_added", function (snapshot) {


      if (snapshot.val().sender == "PS") {
        setSender = "<li class='self'>"   + snapshot.val().message + "</li>";
      } else {
        setSender = "<li class=''>" + "{{ patient.user }}" + ": " + snapshot.val().message + "</li>";
      }


      var html = "";
      html += setSender ;

      document.getElementById("messages").innerHTML += html;
    });
</script>

{% load static %}

<html>
  <head>
    <title>MindBliss</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/new_styles.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <style>
      .block-chat{
          width: 50%;
          margin: auto;
          padding-top: 50px ;
          background-color: white ;
        }
        #messages{
          list-style-type: none !important;
          padding-left: 0;
        }
        #messages li{
          text-align: left;
          height: 24px;
          background-color: rgb(232, 232, 232);
          padding-left: 10px;
          padding-bottom: 10px !important;
          margin-bottom: 10px;
          border-radius: 12px;
        }
        #messages li.self{
          background-color: lightgreen;
          text-align: right;
          padding-right: 10px;
        }
    </style>
  
  </head>
  <body style="background-image: url('{% static 'img/background5.png' %}')">
    {% include "Header.html" %}

    <div class="block-chat">
      <h4 class="mb-4">Chatting with patient </h4>

      <ul id="messages">
      </ul>

      <form onsubmit="return sendMessage();">
        <input type="text" id="message" class="w-80" />
        <input type="submit" value="SEND" class="px-4 w-20" />
      </form>
    </div>

    {% include "Footer.html" %}
  </body>
</html>

templates/checkout.html

<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="background.css" rel="stylesheet" type="text/css">
         
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
         
       
<link rel="stylesheet" href="css/style.css">

    </head>
    <body>
        <header>
<div class="top" >
<button class="button"><b>contact us<b></button>
<img src="#" alt=logo>
<h1> Mind Bliss<h1>
</header>
</div>
<div class="topnav">
  <a href="#" >Home</a>
  <a href="Searchpsychologist.html" class="active">Search psychologist</a>
  <a href="#">Blogs</a>
 <a href="#">User stories</a>
  <a href="#">Settings</a>
  <a href="#">Personality test</a>
<input type="text" placeholder="Search">
</div>
<div class="margin"></div>

 <!----container----------------------->
<div class="container">
	<div class="row">
  <div class="col-75">
    <div class="containercheckout">

        <div class="row">
          <div class="col-50">
            <h3>Personal Information</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input class="checkoutInput" type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input class="checkoutInput" type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input class="checkoutInput" type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input class="checkoutInput" type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input class="checkoutInput" type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input class="checkoutInput" type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input class="checkoutInput" type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input class="checkoutInput" type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input class="checkoutInput" type="text" id="expmonth" name="expmonth" placeholder="September">

            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input class="checkoutInput" type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input class="checkoutInput" type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        
     <input type=button type="submit" value="Check out" class="btn" onClick="parent.location='ChatDoctor.html'">
    </div>
  </div>
</div>

</div>

<!-------------------------------------------------footer--------------------->
		
<footer class="footer-distributed">
<div class="footer-left">
 
<h3>MIND<span>BLISS</span></h3>
 
<p class="footer-links">
<a href="#">Home</a>
	
<a href="#">Blog</a>
<a href="#">Pricing</a>
	
<a href="#">About</a>
	
<a href="#">Faq</a>
<a href="#">Contact</a>
</p>
 
<p class="footer-company-name">webdevtrick &copy; 2019</p>
</div>
 
<div class="footer-center">
 
<div>
<i class="fa fa-map-marker"></i>
		<p><span>21 Revolution Street</span> Delhi, India</p>
		</div>
 
		<div>
		<i class="fa fa-phone"></i>
		<p>+1 555 123456</p>
		</div>
 
		<div>
		<i class="fa fa-envelope"></i>
		<p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
		</div>
 
		</div>
 
		<div class="footer-right">
 
		<p class="footer-company-about">
		<span>About the company</span>
	Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
		</p>
 
		<div class="footer-icons">
 
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
 
		</div>
 
		</div>
 
		</footer>

    </body>
</html>

templates/createAppointment.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="login"> 

  <h5 class="text-start">Doctor reserved Appointments</h5>
  {% for appointment in appointments %}
    {% comment %} {% if appointment.date|date:"d M Y" > now %} {% endcomment %}
    <p class="text-start"> {{ appointment.date }} - {{ appointment.time }}  </p>
    {% comment %} {% endif %} {% endcomment %}
  {% endfor %} 

  <hr>

  <h5 class="text-center mt-3">Create Appointment</h5>
  <form method="POST" action=""> 
    {% csrf_token %}
    <label for="id_time">Time:</label>
    {% comment %} <input type="time" min="09:00" max="18:00" > {% endcomment %}

    <select name="time" required="" id="id_time" class="form-control w-100">
      <option value="09:00:00" > 09 AM </option>
      <option value="10:00:00" > 10 AM </option>
      <option value="11:00:00" > 11 AM </option>
      <option value="12:00:00" > 12 PM </option>
      <option value="13:00:00" > 01 PM </option>
      <option value="14:00:00" > 02 PM </option>
      <option value="15:00:00" > 03 PM </option>
      <option value="16:00:00" > 04 PM </option>
      <option value="17:00:00" > 05 PM </option>
      <option value="118:00:00" > 06 PM </option>
    </select>

    <label for="id_date">Date:</label>
    <input type="date" name="date" required="" min="2020-01-01" max="2025-01-01" id="id_date" class="form-control w-100">

    <br />
    <br />
    <input type="submit" value="Book Appointmentz" />
  </form>

  <script>
    var today = new Date().toISOString().split('T')[0];
    document.getElementsByName("date")[0].setAttribute('min', today);

    var maxDate = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 14 ).toISOString().split('T')[0];
    document.getElementsByName("date")[0].setAttribute('max', maxDate);
  </script>
 

</div>

{% endblock %}

templates/doctorlist.html

<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <link href="background.css" rel="stylesheet" type="text/css">
         
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
         
         
<link rel="stylesheet" href="css/style.css">
    </head>
    <body>
      <header>
<div class="top" >
<button class="button"><b>contact us<b></button>
<img src="#" alt=logo>
<h1> Mind Bliss<h1>
</header>
</div>
<body>
<div class="topnav">
  <a href="dashboard.html" >Home</a>
  <a href="searchpsychologist.html" class= "active">Search Phychologist</a>
  <a href="blog page.html">Blogs</a>
 <a href="userstories.html">User stories</a>
  <a href="settings main page.html">Settings</a>
  <a href="#">Personality test</a>
  <a href="#">Personality test</a>
</div>
<div class="margin"></div>
<div class="containerList">
	<div style="background:#fff;padding: 1px;"> 
		<h3 style="text-align: center;font-size: 20px;">
			Psychologists
		</h3>
	</div>
</div>
 <!----container----------------------->
<div class="container">
	
		<div class="row">
  <div class="leftcolumn">
    <div class="card">
    	<div><img src="images/johnwicks.jpg" style="height: 250px;width: 373px;"> </div>
    	<a href="Profile.html" style="float: none; text-decoration: none; color:black; "><h2>Mr.John Wicks</h2></a>
      
      <h5>Psychologist</h5>
      
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, 
pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus...</p>
<a href="checkout.html" class="checkout">Check Out</a>
    </div>
    <div class="card">
    	<div><img src="images/images.jfif" style="height: 250px;width: 373px;"> </div>
    	<a href="Profile.html" style="float: none;text-decoration: none;color:black;"><h2>Mr.Peterson</h2></a>
     
      <h5>Psychologist</h5>
      
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, 
pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus...</p>
<a href="checkout.html" class="checkout">Check Out</a>
    </div>
    <div class="card">
    	<div><img src="images/Usama.png" style="height: 250px;width: 373px;"> </div>
    	<a href="Profile.html" style="float: none;text-decoration: none;color:black;"><h2>Mr.Usama</h2></a>
      
      <h5>Psychologist</h5>
      
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, 
pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus...</p>
<a href="checkout.html" class="checkout">Check Out</a>
    </div>
  </div>
</div>
</div>

<!-------------------------------------------------footer--------------------->
		
<footer class="footer-distributed">
<div class="footer-left">
 
<h3>MIND<span>BLISS</span></h3>
 
<p class="footer-links">
<a href="#">Home</a>
	
<a href="#">Blog</a>
<a href="#">Pricing</a>
	
<a href="#">About</a>
	
<a href="#">Faq</a>
<a href="#">Contact</a>
</p>
 
<p class="footer-company-name">webdevtrick &copy; 2019</p>
</div>
 
<div class="footer-center">
 
<div>
<i class="fa fa-map-marker"></i>
		<p><span>21 Revolution Street</span> Delhi, India</p>
		</div>
 
		<div>
		<i class="fa fa-phone"></i>
		<p>+1 555 123456</p>
		</div>
 
		<div>
		<i class="fa fa-envelope"></i>
		<p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
		</div>
 
		</div>
 
		<div class="footer-right">
 
		<p class="footer-company-about">
		<span>About the company</span>
	Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
		</p>
 
		<div class="footer-icons">
 
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
 
		</div>
 
		</div>
 
		</footer>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% include 'Header.html' %}


<h1></h1>


{% include 'Footer.html' %}
{% endblock %} 